adding function errors_handler
Prevent an error ```ImportError: cannot import name 'errors_handler' from 'userbot.events' (/opt/PaperplaneExtended/userbot/events.py)``` causing by:
  File "/opt/PaperplaneExtended/userbot/modules/github.py", line 2, in <module>
    from userbot.events import register, errors_handler